name: Semgrep SAST Scan

on:
  push:
    branches:
      - NuevaRama
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el código
        uses: actions/checkout@v4

      - name: Instalar Semgrep
        run: python -m pip install semgrep

      - name: Ejecutar análisis de seguridad
        run: |
          semgrep scan --config=auto --error .

      - name: Mostrar resultados
        run: cat semgrep-results.sarif
